version: '3.9'
services:
  nginx:
    ports:
      - "3000:80"
  app:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
      - MONGO_USER=ah
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=secret
    command: npm run dev
    
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ah
      - MONGO_INITDB_ROOT_PASSWORD=mypassword


